### ISSUE TITLE
add WP-CLI (code and info provided)

### ISSUE THREAD

**Issue by David-Else** [nezhar/wordpress-docker-compose#11]
Hi, it would be great to add WP-CLI by default!

I have only just started to use Docker, and hacked this together which seems to work. Does this look good to you? I am a bit worried I may have caused problems, I don't know what I am doing yet. I based it on this:

https://stackoverflow.com/questions/50999848/how-to-run-wp-cli-in-docker-compose-yml

Maybe it would be beneficial to add something like this to the official repo?

docker-compose.yml
```
  wpcli:
    image: wordpress:cli
    user: xfs
    volumes:
      - ./wp-app:/var/www/html:z
    depends_on:
      - db
      - wordpress
    networks:
      - wordpress-network
```
Now on the command line you can:

`alias wp="sudo docker-compose run --rm wpcli"`

and type:

```
wp plugin list
Starting final_db_1 ... done
Starting final_wordpress_1 ... done
+---------+----------+--------+---------+
| name    | status   | update | version |
+---------+----------+--------+---------+
| akismet | inactive | none   | 4.0.8   |
+---------+----------+--------+---------+
```
