### ISSUE TITLE
How to deal with the user permisions on the folders?

### ISSUE THREAD

**Issue by markdimi** [nezhar/wordpress-docker-compose#28]
The folder that are created after running 'docker-compose up -d` belong to the root user. How to deal with the user permissions? 

I want to create a complete development environment thus I need complete access to wp-content for themes and plugins.

**Comment by nezhar** [comment]
I also had a similar issue on PHP containers for Laravel. I solved this using an entrypoint script: https://github.com/nezhar/laravel-docker-compose/tree/master/docker/php

I may add this also here in future.

**Comment by henripfr** [comment]
Hi, 
I'm testing your amazing job, but I still can't fix that user permissions folders.
For instance with the WP Backoffice, I can't upload medias. 

How did you by pass that issue ?

**Comment by markdimi** [comment]
Even though I don't like messing with permissions of folders, I changed them manually. Inside the root folder I give `sudo chown -R $USER:$USER .`

Don't forget the last dot.

**Comment by henripfr** [comment]
> Even though I don't like messing with permissions of folders, I changed them manually. Inside the root folder I give `sudo chown -R $USER:$USER .`
> 
> Don't forget the last dot.
Hello, 
That's exactly what I finished by doing. 
Thanks for your reply !

**Comment by nezhar** [comment]
Also you may try to run the container as an arbitrary user as provided in the docs of the PHP Docker image, as this is the base of the Wordpress image: https://hub.docker.com/_/php/

All you need for this is to extend the environmets of the wordpress service:

```
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      APACHE_RUN_USER: 1000
      APACHE_RUN_GROUP: 1000
```
