### ISSUE TITLE
Volume mounting issue

### ISSUE THREAD

**Issue by michealjroberts** [nezhar/wordpress-docker-compose#32]
This does not work:

      - ./wp-app:/var/www/html # Full wordpress project
      - ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      - ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development

**Comment by palomnik** [comment]
I am having this problem also.  It was working, and then suddenly was not.  It stopped working when I tried to run docker-compose on a mounted share in VirtualBox, which I have learned is a bad idea.  Since then, it keeps happening.  I have pruned and reinstalled docker, but still have the problem, although going back to a folder in my home directory (and my UID is in the docker group).

Here is the error I get:

`ERROR: for strannik_wpcli_1  Cannot start service wpcli: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/var/www/html\") set in config.json failed: permission denied": unknown

ERROR: for wpcli  Cannot start service wpcli: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/var/www/html\") set in config.json failed: permission denied": unknown

ERROR: Encountered errors while bringing up the project.
`
phpmyadmin is working fine.  All of the containers are running. If I go to the site, apache loads, but complains about permission to load "/".

I am using docker from docker.io:
Docker version 18.09.7, build 2d0083d
docker-compose version 1.24.1, build 4667896b

This is obviously some permissions problem with mounting on my Linux VM.

I have the same files copied to my mac, where it comes up and runs with no problem.

I cannot figure out where the problem is coming from.

**Comment by palomnik** [comment]
## Problem Fixed and a Request for a Fix to the Master Branch

OK, I rolled back my VM to a snapshot which revealed an older version of the site files with different file permissions.  In moving the files through Dropbox in Windows, the file permissions had changed from 755 for directories and 644 for files to 770 for everything.  I created the following script to reset any permissions

> #! /bin/bash
> 
> find . -type d -exec chmod 755 {} +
> find . -type f -exec chmod 646 {} +

Then the site loaded, except the database was empty.

I noticed these lines in the YAML file:

>     volumes:
>     - ./wp-data:/docker-entrypoint-initdb.d
>      - db_data:/var/lib/mysql

I wondered why the path "./" is made explicit for wp-data and not for db_data?
It worked before, but not this time for some reason.  It seems that the path should be explicit here as well, so I changed it to:

>      - ./db_data:/var/lib/mysql

And now it works!  Yay!

I recommend that the change to make the path explicit for db_data be included in the master branch of the repository.

**Comment by simonh1000** [comment]
I'm having issues too. With the setup below php files in the root directory of my theme are found, but the screenshot.png and the css/js files in the `/dist` directory are not. Any ideas?

```
services:
  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - ${IP}:80:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      # - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      - ../af2016/:/var/www/html/wp-content/themes/af2016 # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
```
