### ISSUE TITLE
Add custom entrypoint to solve file permission issue

### ISSUE THREAD

**Issue by nezhar** [nezhar/wordpress-docker-compose#35]
Based on https://github.com/nezhar/wordpress-docker-compose/pull/34

**Comment by chungchi300** [comment]
is it mean there is a fix for file upload permission error? Since I am suffering from it now, but again thanks for this great setup that makes the WordPress development process more easier

**Comment by nezhar** [comment]
Hi @chungchi300 

The entrypoint is one way, but it would add complexity to the repository, which I would like to avoid if possible.

There is another way that may be a bit better. Would you like to try adding the user attribute to you docker-compose.yml in the wp service?

```yml
services:
  wp:
    user: "${UID}:${GID}"
    image: wordpress:latest
    ...  
```
