### ISSUE TITLE
php.ini settings for phpmyadmin container

### ISSUE THREAD

**Issue by flip111** [nezhar/wordpress-docker-compose#51]
At the moment only php settins from the wordpress container are exposed.

I want to import a 60 MB SQL file (13 MB zipped) into phpMyAdmin but can't because of php limits.

I need to change the settings described in this answer https://stackoverflow.com/a/11646202/1833322

**Comment by grynczel** [comment]
You can simply use the UPLOAD_LIMIT property in your docker-compose.yml
```
pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 512M
    ports:
      - ${IP}:8080:80
    links:
      - db:db
```
