### ISSUE TITLE
WP-CLI: Error establishing a database connection

### ISSUE THREAD

**Issue by joelsmith80** [nezhar/wordpress-docker-compose#69]
Not sure what I'm doing wrong here. I'm following all of the instructions, not changing any default variables, and while WordPress and PHPMyAdmin work perfectly, I can't get wp-cli to work. Any time I run the command in the instructions, I get `Error establishing a database connection`. Any time I try to restart it via the Docker dashboard, I get the same error. What gives? What database credentials is wp-cli using? What else can I do to configure this?

If it makes a difference, I'm on a new MacBook Pro with the M1 chip. (This has caused problems with other programs; don't know if it's an issue here.)

**Comment by Synkronice** [comment]
Hey,
Same here, just wait few minutes and it works fine for me

**Comment by satcar77** [comment]
> Since March 2021, WordPress images use a customized wp-config.php that pulls the values directly from the environment variables defined above (see wp-config-docker.php in docker-library/wordpress#572 and docker-library/wordpress#577). As a result of reading environment variables directly, the cli container also needs the same set of environment variables to properly evaluate wp-config.php.


Pass in the same environment variables from wordpress service to the wpcli and it should work.

**Comment by nguyenlamlll** [comment]
@satcar77 May you explain a little bit more? I don't get the part "pass in the same environment variables". I think I have cloned the branch master, simply `docker-compose up -d` and then `docker-compose run --rm wpcli plugin list` as the readme file says, but it does not work. Got the same database connection error.

**Comment by nguyenlamlll** [comment]
Ok, silly me. I'm sorry. But I think I got what is required. The wpcli section in the current `docker-compose.yml` does not have the matching environment section as wp's. So, I ensure everything is matching.

```
services:
  wp:
    image: wordpress:5
    ports:
      - ${IP}:80:80
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    **environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"**
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    depends_on:
      - db
      - wp

```

Then, ` docker-compose run --rm  wpcli user list`. It works!

Thank you!
