### ISSUE TITLE
wsl2 Ubuntu host - cannot update from wp-admin dashboard and wpcli restricted use

### ISSUE THREAD

**Issue by nicholasvad** [nezhar/wordpress-docker-compose#74]
### Think this works pretty well
The first thing to say is that I think this `docker-compose` solution for WordPress is very good.  I like it and I hope that I can use it for development.
### Can only install and update manually - cannot update from wp-admin dashboard
I am using wsl2 on Windows 10 with Docker Desktop. I am using my Docker commands from inside my wsl2 Ubuntu 'host' and my files are same in a wsl2 Ubuntu machine. This is in line with wsl2 recommendations which say that data files for use with wsl2 should be in a wsl2 machine for faster and more efficient Docker performance.

My main problem is that when I go to install a theme or plugin from wordpress.org, it asks for connection information for FTP or FTPS, namely: `hostname`, `username` and `password`.  Nothing I can think of seems to work.

I can do **manual installations or updates** by downloading the theme or plugin zip file to my Windows host, copying it to my Ubuntu wsl2 machine and unzipping it in the themes or plugins folder respectively.  I can then activate appropriately from wp-admin. I think for updates I should delete the existing theme or plugin and unzip the new one in its place. This is slow, but it works.

However I cannot `update translations\language packs` - I get the same request for FTP credentials.  It doesn't seem ideal for development work given these updating constraints.  Also if I try to upload a zip file for a theme or plugin, I get an error from the url:
`localhost/wp-admin/update.php?action=upload_theme`
> Error: The uploaded file could not be moved to wp-content/uploads/2021/07

#### What I have tried
**Using IP address of wsl2 machine**
From previous experience with wsl2, I know that the IP address changes every time I open up my wsl2 Ubuntu machine. I can find them for each login using:
`$ hostname -I` returns (for example) `172.23.173.162`
`$ cat \etc\resolv.conf` returns (for example) `172.23.160.1`

In my 'hosts' file on my Windows 'host' I have tried adding both these as IP addresses for a 'hostname' for my WP site running in Docker, e.g.:
`172.23.173.162     myhostname`
I find the WordPress website on `http:\\myhostname`, but I can't log in with the same hostname (see below - it reverts to `localhost`):
When I enter my login details at `http:\\myhostname\wp-login.php` I get the error:
> Error: cookies are blocked or not supported by your browser. You must enable cookies to use WordPress.
I repeat my login details below the error message, but the url has removed `myhostname` and replaced it with `localhost`. From the `localhost` hostname, I can log into WP, but I get the error messages above for updates and plugin/theme installations.

**Anything possible using Docker networking?**
I have been using `$ docker-compose up -d` to create the Docker containers.
Then to stop them, I have been using: `$ docker-compose stop`

To start the containers again, I have used either:
`$ docker-compose start` or
`$ docker-compose up`

I wondered if the Docker network might be in the same network, so I inspected the network:
`$ docker network inspect [ID/name for myDockerNetwork]`
These showed the following network:
`172.18.0.1/16` for the range and
`172.18.0.1` for the gateway.
These are clearly a different range to the wsl2 host IP addresses.  I recreated the containers and the range changed to `172.19.0.1/16`, but this was still different to the wsl2 host IP addresses.

**Does anyone have a solution for this problem with updating and uploading plugins or themes?**

I think this issue may also explain why my `wpcli` container isn't working fully.  I can list plugins but I can't update them, delete them or install them using `wpcli` because it shows errors in all cases.

----
For completeness, here is my slightly revised `docker-compose.yml` file. I note that my `wpfiles` directory was owned and in the group of `www-data`.  To get through this, I simply entered:
`$ sudo chown -R username:username wpfiles` to change the ownership of those exposed files and directories in the `wpfiles` directory to my username.

docker-compose.yml
```yaml
version: '3.8'

services:
  mysqldb:
    image: mysql:5.7 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - 3306:3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${WP_USER}"
      MYSQL_PASSWORD: "${WP_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
      - wpnet
    restart: unless-stopped

  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - 80:80
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      # - ./wp-content:/var/www/html/wp-content # this does not work with WP-CLI
      - ./wpfiles:/var/www/html
      #- ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${WP_USER}" # root
      WORDPRESS_DB_PASSWORD: "${WP_PASSWORD}" # "${DB_ROOT_PASSWORD}"
      # Set Apache user uid so that mounted files on wpfiles are accessible
      # Set for Linux where main host user had a uid of 1000; adapt as required
      APACHE_RUN_USER: #1000
      # Didn't try changing Apache group as the new uid seemed to work initially. Now still an issue with this.
      # APACHE_RUN_GROUP: #1000
      WORDPRESS_DEBUG: 1
    depends_on:
      - mysqldb
    networks:
      - wpnet
    restart: unless-stopped

  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wpfiles:/var/www/html
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${WP_USER}" # root
      WORDPRESS_DB_PASSWORD: "${WP_PASSWORD}" # "${DB_ROOT_PASSWORD}"
    depends_on:
      - mysqldb
      - wp
    networks:
      - wpnet

  phpma:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - 8080:80
    depends_on: 
      - mysqldb
    networks:
      - wpnet

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - wpnet

volumes:
  db_data:

networks: 
  wpnet:
```
